# NumPy: Basic to Advanced

## I. The Basics of NumPy

### 1. Why NumPy?

Python lists are flexible but can be slow for large numerical operations. NumPy arrays (`ndarray`) offer:

- **Speed**: Operations are implemented in C, making them much faster.
- **Memory Efficiency**: NumPy arrays consume less memory than Python lists for storing numerical data.
- **Convenience**: A rich ecosystem of functions for:
  - Mathematical operations
  - Logical operations
  - Shape manipulation
  - Sorting and selecting
  - Input/Output (I/O)
  - Discrete Fourier transforms
  - Basic linear algebra
  - Basic statistical operations
  - Random simulation


In [13]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1d}, Shape: {arr1d.shape}, Dtype: {arr1d.dtype}")

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array:\n{arr2d}, Shape: {arr2d.shape}, Dtype: {arr2d.dtype}")

1D Array: [1 2 3 4 5], Shape: (5,), Dtype: int64
2D Array:
[[1 2 3]
 [4 5 6]], Shape: (2, 3), Dtype: int64


In [15]:
zeros_arr = np.zeros((3, 4)) # 3 rows, 4 columns
print(f"Zeros Array:\n{zeros_arr}")

ones_arr = np.ones((2, 3), dtype=int) # Specify data type
print(f"Ones Array:\n{ones_arr}")

# empty_arr = np.empty((2, 2))
# print(f"Empty Array:\n{empty_arr}")

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
[[1 1 1]
 [1 1 1]]


### 2. `np.arange()`

`np.arange()` creates an array with evenly spaced values within a given interval, similar to Python’s built-in `range()` function.

**Syntax**:
```python
np.arange(start, stop, step)


In [16]:
arange_arr = np.arange(0, 10, 2) # Start, Stop (exclusive), Step
print(f"Arange Array: {arange_arr}")

Arange Array: [0 2 4 6 8]


### 3. `np.linspace()`

`np.linspace()` creates an array of evenly spaced numbers over a specified interval. Unlike `np.arange()`, you specify how many values you want, not the step size.

**Syntax**:
```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False)


In [19]:
linspace_arr = np.linspace(0, 10, 10) # Start, Stop (inclusive), Number of samples
print(f"Linspace Array: {linspace_arr}")

Linspace Array: [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


### 5. Array Attributes

NumPy arrays come with several useful attributes:

- `.ndim` – Number of dimensions (axes)  
- `.shape` – Tuple representing the dimensions of the array  
- `.size` – Total number of elements in the array  
- `.dtype` – Data type of the array elements

**Example**:
```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Dimensions (ndim):", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
pri


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimensions: {arr.ndim}")
print(f"Shape: {arr.shape}")
print(f"Size: {arr.size}")
print(f"Data type: {arr.dtype}")

Dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64


### 6. Indexing and Slicing

Indexing and slicing in NumPy are similar to Python lists, but with powerful N-dimensional capabilities.

#### 🟦 1D Array

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Indexing
print("Element at index 1:", arr[1])        # 20

# Slicing
print("Elements from index 1 to 3:", arr[1:4])  # [20 30 40]
print("Every second element:", arr[::2])       # [10 30 50]
print("Reversed array:", arr[::-1])            # [50 40 30 20 10]


In [22]:
a = np.array([10, 20, 30, 40, 50])
print(f"Element at index 2: {a[2]}")
print(f"Slice from index 1 to 3 (exclusive): {a[1:4]}")
print(f"Every other element: {a[1::2]}")

Element at index 2: 30
Slice from index 1 to 3 (exclusive): [20 30 40]
Every other element: [20 40]


In [24]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Element at (0, 1): {b[0, 1]}")
print(f"First row: {b[0, :]}") # Or simply b[0]
print(f"Second column: {b[:, 1]}")
print(f"Sub-array (first 2 rows, first 2 columns):\n{b[:2, :2]}")

Element at (0, 1): 2
First row: [1 2 3]
Second column: [2 5 8]
Sub-array (first 2 rows, first 2 columns):
[[1 2]
 [4 5]]


In [25]:
# Boolean Indexing: Select elements based on a boolean condition.
data = np.array([10, 15, 20, 25, 30])
mask = data > 20
print(mask)
print(f"Elements greater than 20: {data[mask]}")
print(f"Elements greater than 20 (shorthand): {data[data > 20]}")

[False False False  True  True]
Elements greater than 20: [25 30]
Elements greater than 20 (shorthand): [25 30]


In [30]:
# Reshaping and Resizing

arr = np.arange(12)

reshaped_arr = arr.reshape((3, 4))
print(f"Original:\n{arr}\nReshaped:\n{reshaped_arr}")

# -1 can be used for one dimension to be inferred
inferred_shape = arr.reshape((2, -1))
print(f"Inferred Shape:\n{inferred_shape}")

Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Inferred Shape:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# ravel(): Flattens an array into a 1D array (returns a view if possible).

# flatten(): Flattens an array into a 1D array (always returns a copy).

In [31]:
flat_arr_ravel = reshaped_arr.ravel()
flat_arr_flatten = reshaped_arr.flatten()
print(f"Raveled: {flat_arr_ravel}")
print(f"Flattened: {flat_arr_flatten}")


Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
def test():
    '''
    this is demo app
    '''
    return 'All good!'



help(test)

Help on function test in module __main__:

test()
    this is demo app



In [39]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `end

In [32]:
# Stacking and Splitting
# np.vstack(): Stack arrays vertically (row-wise).
# np.hstack(): Stack arrays horizontally (column-wise).
# np.concatenate(): General function to join arrays along an existing axis

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(f"Vertical Stack:\n{np.vstack((a1, a2))}")
print(f"Horizontal Stack: {np.hstack((a1, a2))}")

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(f"Concatenate along axis 0 (rows):\n{np.concatenate((mat1, mat2), axis=0)}")
print(f"Concatenate along axis 1 (columns):\n{np.concatenate((mat1, mat2), axis=1)}")

Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]
Concatenate along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]
